version: '3.3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8080:80
        links:
          - fpm
        volumes:
          - ./:/var/www/laravel_notebook

    fpm:
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        volumes:
          - ./:/var/www/laravel_notebook
        links:
          - mysql

    mysql:
        image: mysql:5.7
        restart: always
        tty: true
        ports:
            - 3351:3306
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=notebooke
            - MYSQL_HOST=%

    phpmyadmin:
        depends_on:
          - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 8090:80
        environment:
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: root


